# Generated by Django 5.2.1 on 2025-10-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_plandiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplan',
            name='total_members',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subplan',
            name='max_member',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subplan',
            name='validity_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
